export const GET_PRODUCTS = "GET_PRODUCTS";

export const CHANGE_PRODUCTS_CATEGORIES = "CHANGE_PRODUCTS_CATEGORIES";
export const CHANGE_PRODUCTS_SORT = "CHANGE_PRODUCTS_SORT";

export const ADD_PRODUCT_TO_CART = "ADD_PRODUCT_TO_CART";
export const REMOVE_PRODUCT_FROM_CART = "REMOVE_PRODUCT_FROM_CART";
