export const GET_PRODUCTS = "GET_PRODUCTS";

export const CHANGE_PRODUCTS_CATEGORIES = "CHANGE_PRODUCTS_CATEGORIES";
export const CHANGE_PRODUCTS_SORT = "CHANGE_PRODUCTS_SORT";

export const ADD_PRODUCT_TO_CART = "ADD_PRODUCT_TO_CART";
export const REMOVE_POSITION_FROM_CART = "REMOVE_POSITION_FROM_CART";

export const INCREMENT_POSITION_IN_CART = "INCREMENT_POSITION_IN_CART";
export const DECREMENT_POSITION_IN_CART = "DECREMENT_POSITION_IN_CART";
export const CLEAR_CART = "CLEAR_CART";
